apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zalando

resources:
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.13.0/manifests/configmap.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.13.0/manifests/operator-service-account-rbac.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.13.0/manifests/postgres-operator.yaml
  - https://raw.githubusercontent.com/zalando/postgres-operator/v1.13.0/manifests/api-service.yaml
  - namespace.yaml
  - postgresql.yaml
  - secret.yaml
