resources:
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
  - namespace.yaml
  - rbac.yaml
  - prometheus.yaml
  - service.yaml

namespace: prometheus
