apiVersion: v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Pod
metadata:
  # This name uniquely identifies the Deployment
  name: mc
spec:
  containers:
    - name: minio
      # Pulls the default Minio image from Docker Hub
      command: ["tail"]
      args: ["-f", "/dev/null"]
      image: minio/minio:latest
      env:
        # Minio access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
